# Generated by Django 6.0.6 on 2026-06-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='activate',
            field=models.BooleanField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario'),
        ),
    ]
