# Generated by Django 6.0.6 on 2026-06-15 01:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('create_date', models.DateField(auto_created=True, default=datetime.date(2026, 6, 14))),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('J', 'Pessoa juridica'), ('F', 'Pessoa Fisica')], max_length=1)),
                ('fantasy_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='vendedores.representative')),
            ],
        ),
    ]
