# Generated by Django 6.0.6 on 2026-06-15 02:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Razão Social'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='representative',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='people', to='vendedores.representative', verbose_name='Vendedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateField(auto_created=True, default=datetime.date(2026, 6, 14), verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fantasy_name',
            field=models.CharField(max_length=50, verbose_name='Nome Fantasia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='type',
            field=models.CharField(choices=[('J', 'Pessoa juridica'), ('F', 'Pessoa Fisica')], max_length=1, verbose_name='Tipo'),
        ),
    ]
