# Generated by Django 6.0.6 on 2026-06-24 14:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_client_vendedor_client_company_name_and_more'),
        ('vendedores', '0002_alter_representative_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2026, 6, 24, 11, 12, 21, 498017), verbose_name='Data de abertura'),
        ),
        migrations.AlterField(
            model_name='client',
            name='representative',
            field=models.ForeignKey(limit_choices_to={'activate': True}, on_delete=django.db.models.deletion.PROTECT, related_name='people', to='vendedores.representative', verbose_name='Vendedor'),
        ),
    ]
