# Generated by Django 6.0.6 on 2026-06-24 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_client_create_date_alter_client_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateField(auto_created=True, default=datetime.datetime(2026, 6, 24, 13, 37, 0, 51387), verbose_name='Data de abertura'),
        ),
    ]
