# Generated by Django 6.0.6 on 2026-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_client_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de abertura'),
        ),
    ]
